
package FormBarCode;

import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.image.BufferedImage;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import net.sourceforge.barbecue.Barcode;
import net.sourceforge.barbecue.BarcodeFactory;
import net.sourceforge.barbecue.BarcodeImageHandler;
import net.sourceforge.barbecue.output.OutputException;

/**
 *
 * @author CSR
 */
public class JFrameBarCode extends javax.swing.JFrame {

    /**
     * Creates new form JFrameBarCode1
     */
    public JFrameBarCode() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBarCode = new javax.swing.JLabel();
        jButtonBarCode = new javax.swing.JButton();
        jButtonImportBarCode = new javax.swing.JButton();
        jButtonExportLabELS = new javax.swing.JButton();
        jButtonImprimir = new javax.swing.JButton();
        jLabelName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtBarName = new javax.swing.JLabel();
        jLabelCode = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        jLabelM10R = new javax.swing.JLabel();
        jButtonCLEaner = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtBarCode.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonBarCode.setText("BarCode");
        jButtonBarCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBarCodeActionPerformed(evt);
            }
        });

        jButtonImportBarCode.setText("Importar BarCode");
        jButtonImportBarCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportBarCodeActionPerformed(evt);
            }
        });

        jButtonExportLabELS.setText("Exportar LabELS");
        jButtonExportLabELS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportLabELSActionPerformed(evt);
            }
        });

        jButtonImprimir.setText("Imprimir");
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });

        jLabelName.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        jLabelName.setText("NOMBRE:");

        txtName.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        txtName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtBarName.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        txtBarName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBarName.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelCode.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        jLabelCode.setText("CÓDIGO:");

        txtCode.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        txtCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeActionPerformed(evt);
            }
        });

        jLabelM10R.setFont(new java.awt.Font("Monaco", 1, 22)); // NOI18N
        jLabelM10R.setText("M10R");

        jButtonCLEaner.setText("-|-");
        jButtonCLEaner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCLEanerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtBarName, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonBarCode)
                                .addGap(124, 124, 124)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonImportBarCode)
                            .addComponent(jButtonExportLabELS)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabelCode)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jLabelM10R))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabelName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButtonCLEaner)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonImprimir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(txtBarCode, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabelM10R)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCode)
                    .addComponent(jLabelName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtBarCode, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBarName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBarCode)
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButtonImportBarCode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExportLabELS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonImprimir)
                            .addComponent(jButtonCLEaner))
                        .addContainerGap(12, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBarCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBarCodeActionPerformed
        // TODO add your handling code here:
        Barcode barcode = null;
        String namecode = "";
        try {
            barcode = BarcodeFactory.createCode128(txtCode.getText());
            namecode = (txtName.getText());
        } catch (Exception e) {
        }
        barcode.setDrawingText(true);
        barcode.setBarWidth(2);
        barcode.setBarHeight(60);
        BufferedImage image = new BufferedImage(500, 100, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g = (Graphics2D) image.getGraphics();
        try {
            barcode.draw(g, 5, 20);
        } catch (Exception e) {
        }
        ImageIcon icon = new ImageIcon(image);
        txtBarCode.setIcon(icon);
        txtBarName.setText(namecode);
    }//GEN-LAST:event_jButtonBarCodeActionPerformed

    private void jButtonImportBarCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportBarCodeActionPerformed
        // TODO add your handling code here:
        Clipboard cb = Toolkit.getDefaultToolkit().getSystemClipboard();
        ImageIcon image = (ImageIcon) txtBarCode.getIcon();
        ImageSelectionCode dh = new ImageSelectionCode(image.getImage());
        cb.setContents(dh, null);
    }//GEN-LAST:event_jButtonImportBarCodeActionPerformed

    private void jButtonExportLabELSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportLabELSActionPerformed
        // TODO add your handling code here:
        Barcode barcode = null;
        try {
            barcode = BarcodeFactory.createCode39(txtCode.getText(), true);
        } catch (Exception e) {
        }
        barcode.setDrawingText(false);
        barcode.setBarWidth(2);
        barcode.setBarHeight(60);
        try {
            FileOutputStream fos = new FileOutputStream("/Users/CSR/Downloads/LabELS1.png");
            try {
                BarcodeImageHandler.writePNG(barcode, fos);
            } catch (OutputException ex) {
                Logger.getLogger(JFrameBarCode.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(JFrameBarCode.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonExportLabELSActionPerformed

    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
        // TODO add your handling code here:
        Barcode barcode = null;
        try {
            barcode = BarcodeFactory.createCode39(txtCode.getText(), true);
        } catch (Exception e) {
        }
        barcode.setDrawingText(false);
        barcode.setBarWidth(2);
        barcode.setBarHeight(60);
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setPrintable(barcode);
        if (job.printDialog()){
            try {
                job.print();
            } catch (PrinterException ex) {
                Logger.getLogger(JFrameBarCode.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonImprimirActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeActionPerformed

    private void jButtonCLEanerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCLEanerActionPerformed
        // TODO add your handling code here:
        String none = "";
        txtCode.setText(none);
        txtName.setText(none);
        txtBarName.setText(none);
    }//GEN-LAST:event_jButtonCLEanerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameBarCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameBarCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameBarCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameBarCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameBarCode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBarCode;
    private javax.swing.JButton jButtonCLEaner;
    private javax.swing.JButton jButtonExportLabELS;
    private javax.swing.JButton jButtonImportBarCode;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JLabel jLabelCode;
    private javax.swing.JLabel jLabelM10R;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel txtBarCode;
    private javax.swing.JLabel txtBarName;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
